# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
   {id: 0, size: 0.134275},
   {id: 3, size: 0.134275},
   {id: 2, size: 0.134275},
   {id: 1, size: 0.134275},
   {id: 4, size: 0.134275}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    # {
    #   name: 'my_bundle',
    #   layout:
    #     [
    #       {id: 0, size: 0.134275, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 4, size: 0.134275, x: -0.2108, y: -0.2899, z: -0.0468, qw: 0.9969, qx: 0.0764, qy: 0.0192, qz: -0.0063},
    #       {id: 1, size: 0.134275, x: 0.2116, y: 0.2912, z: 0.0397, qw: 0.9986, qx: 0.0406, qy: -0.0323, qz: -0.0142},
    #       {id: 3, size: 0.134275, x: 0.2103, y: -0.2914, z: -0.0377, qw: 0.9966, qx: 0.0768, qy: -0.0307, qz: -0.0019},
    #       {id: 2, size: 0.134275, x: -0.2124, y: 0.2939, z: 0.0333, qw: 0.9986, qx: 0.0482, qy: 0.0228, qz: 0.0024}
    #     ]
    # }
  ]
